#!/usr/bin/env bash
# Save existing env vars
export _CONDA_SET_QTWEBENGINEPROCESS_PATH="${QTWEBENGINEPROCESS_PATH:-}"
export _CONDA_SET_QTWEBENGINE_RESOURCES_PATH="${QTWEBENGINE_RESOURCES_PATH:-}"
export _CONDA_SET_QTWEBENGINE_LOCALES_PATH="${QTWEBENGINE_LOCALES_PATH:-}"
export _CONDA_SET_QTWEBENGINE_DISABLE_SANDBOX="${QTWEBENGINE_DISABLE_SANDBOX:-}"

# Set paths to point to the conda prefix
export QTWEBENGINEPROCESS_PATH="$CONDA_PREFIX/libexec/QtWebEngineProcess"
export QTWEBENGINE_RESOURCES_PATH="$CONDA_PREFIX/resources"
export QTWEBENGINE_LOCALES_PATH="$CONDA_PREFIX/translations/qtwebengine_locales"
export QTWEBENGINE_DISABLE_SANDBOX=1
