#!/usr/bin/env bash
# Restore env vars or unset them
if [ -n "${_CONDA_SET_QTWEBENGINEPROCESS_PATH}" ]; then
    export QTWEBENGINEPROCESS_PATH="${_CONDA_SET_QTWEBENGINEPROCESS_PATH}"
else
    unset QTWEBENGINEPROCESS_PATH
fi
unset _CONDA_SET_QTWEBENGINEPROCESS_PATH

if [ -n "${_CONDA_SET_QTWEBENGINE_RESOURCES_PATH}" ]; then
    export QTWEBENGINE_RESOURCES_PATH="${_CONDA_SET_QTWEBENGINE_RESOURCES_PATH}"
else
    unset QTWEBENGINE_RESOURCES_PATH
fi
unset _CONDA_SET_QTWEBENGINE_RESOURCES_PATH

if [ -n "${_CONDA_SET_QTWEBENGINE_LOCALES_PATH}" ]; then
    export QTWEBENGINE_LOCALES_PATH="${_CONDA_SET_QTWEBENGINE_LOCALES_PATH}"
else
    unset QTWEBENGINE_LOCALES_PATH
fi
unset _CONDA_SET_QTWEBENGINE_LOCALES_PATH

if [ -n "${_CONDA_SET_QTWEBENGINE_DISABLE_SANDBOX}" ]; then
    export QTWEBENGINE_DISABLE_SANDBOX="${_CONDA_SET_QTWEBENGINE_DISABLE_SANDBOX}"
else
    unset QTWEBENGINE_DISABLE_SANDBOX
fi
unset _CONDA_SET_QTWEBENGINE_DISABLE_SANDBOX
